### ISSUE TITLE
Check label length

### ISSUE THREAD

**Issue by cranst0n** [darkxanter/punycode_converter#1]
Hello. Not sure if you're actively maintaining this library but it fills a need I have but I've run into an issue where the encoding/decoding will allow labels of size greater than 63 characters, which violates the RFC. Is there a way to add this? Relevant line appears to be here:

https://github.com/darkxanter/punycode_converter/blob/61ebee96d0d71f2c357f8e0e1988de231b9b41b0/lib/src/punycode_converter.dart#L248C30-L248C30

If you're not maintaining this, then I'll fork and make the necessary changes myself. Appreciate the useful library!

**Comment by darkxanter** [comment]
New version 0.2.0 published.
